/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface WjStockPrice {
    }
}
declare global {
    interface HTMLWjStockPriceElement extends Components.WjStockPrice, HTMLStencilElement {
    }
    var HTMLWjStockPriceElement: {
        prototype: HTMLWjStockPriceElement;
        new (): HTMLWjStockPriceElement;
    };
    interface HTMLElementTagNameMap {
        "wj-stock-price": HTMLWjStockPriceElement;
    }
}
declare namespace LocalJSX {
    interface WjStockPrice {
    }
    interface IntrinsicElements {
        "wj-stock-price": WjStockPrice;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "wj-stock-price": LocalJSX.WjStockPrice & JSXBase.HTMLAttributes<HTMLWjStockPriceElement>;
        }
    }
}
