/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface WjSpinner {
    }
    interface WjStockFinder {
    }
    interface WjStockPrice {
        "stockSymbol": string;
    }
}
export interface WjStockFinderCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLWjStockFinderElement;
}
declare global {
    interface HTMLWjSpinnerElement extends Components.WjSpinner, HTMLStencilElement {
    }
    var HTMLWjSpinnerElement: {
        prototype: HTMLWjSpinnerElement;
        new (): HTMLWjSpinnerElement;
    };
    interface HTMLWjStockFinderElement extends Components.WjStockFinder, HTMLStencilElement {
    }
    var HTMLWjStockFinderElement: {
        prototype: HTMLWjStockFinderElement;
        new (): HTMLWjStockFinderElement;
    };
    interface HTMLWjStockPriceElement extends Components.WjStockPrice, HTMLStencilElement {
    }
    var HTMLWjStockPriceElement: {
        prototype: HTMLWjStockPriceElement;
        new (): HTMLWjStockPriceElement;
    };
    interface HTMLElementTagNameMap {
        "wj-spinner": HTMLWjSpinnerElement;
        "wj-stock-finder": HTMLWjStockFinderElement;
        "wj-stock-price": HTMLWjStockPriceElement;
    }
}
declare namespace LocalJSX {
    interface WjSpinner {
    }
    interface WjStockFinder {
        "onWjSymbolSelected"?: (event: WjStockFinderCustomEvent<string>) => void;
    }
    interface WjStockPrice {
        "stockSymbol"?: string;
    }
    interface IntrinsicElements {
        "wj-spinner": WjSpinner;
        "wj-stock-finder": WjStockFinder;
        "wj-stock-price": WjStockPrice;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "wj-spinner": LocalJSX.WjSpinner & JSXBase.HTMLAttributes<HTMLWjSpinnerElement>;
            "wj-stock-finder": LocalJSX.WjStockFinder & JSXBase.HTMLAttributes<HTMLWjStockFinderElement>;
            "wj-stock-price": LocalJSX.WjStockPrice & JSXBase.HTMLAttributes<HTMLWjStockPriceElement>;
        }
    }
}
